import java.util.Arrays;
import java.util.NavigableSet;
import java.util.TreeSet;
import java.util.stream.Collectors;

public class LuckyOne {
    /**
     * Given is an array A, of the length N of positive integers
     * The lucky number is generated by performing the following operation at
     * most N-1 times on the given array A
     * - Select the minimum and maximum elements from the array, remove then,
     * nd let diff = maximum - minimum
     * - if diff is not present in array A, then append it into its correct position in array
     * Print lucky number from array A
     */

    public Integer getLuckyNo(int N, int[] A) {
        NavigableSet<Integer> intSet = Arrays.stream(A)
                .boxed()
                .collect(Collectors.toCollection(TreeSet::new));

        for (int i=0; i<N-1; i++) {
            if (intSet.size() < 2)
                break;

            Integer max = intSet.pollLast();
            Integer min = intSet.pollFirst();

            assert min != null;
            assert max != null;
            Integer diff = max - min;

            intSet.add(diff);
        }

        return intSet.stream()
                .reduce(0, (acc, digit) -> acc * 10 + digit);
    }
}
